-- 일일공방 (Daily Workshop) 데이터베이스 스키마
-- Supabase PostgreSQL에서 실행

-- 1. 유저 테이블 (익명 로그인 지원)
CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    username VARCHAR(50) UNIQUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    gold INTEGER DEFAULT 0
);

-- 2. 원소(단어) 테이블
CREATE TABLE IF NOT EXISTS elements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    emoji VARCHAR(10),
    is_base_element BOOLEAN DEFAULT FALSE,
    depth INTEGER DEFAULT 1, -- 난이도 레벨 (기본 원소=1, 조합할수록 증가)
    discovered_by UUID REFERENCES users(id),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. 조합 레시피 테이블
CREATE TABLE IF NOT EXISTS recipes (
    input_a BIGINT REFERENCES elements(id),
    input_b BIGINT REFERENCES elements(id),
    result BIGINT REFERENCES elements(id),
    PRIMARY KEY (input_a, input_b)
);

-- 4. 일일 챌린지 테이블 (매일 목표 단어)
CREATE TABLE IF NOT EXISTS daily_challenges (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL UNIQUE,
    target_element_id BIGINT REFERENCES elements(id),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. 일일 진행 상황 테이블
CREATE TABLE IF NOT EXISTS daily_progress (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES users(id),
    challenge_id BIGINT REFERENCES daily_challenges(id),
    date DATE DEFAULT CURRENT_DATE,
    found_elements BIGINT[],
    move_count INTEGER DEFAULT 0,
    start_time TIMESTAMPTZ DEFAULT NOW(),
    is_completed BOOLEAN DEFAULT FALSE,
    completed_at TIMESTAMPTZ,
    UNIQUE(user_id, date)
);

-- 6. 기본 4원소 삽입 (depth=1)
INSERT INTO elements (name, emoji, is_base_element, depth) VALUES
    ('물', '💧', TRUE, 1),
    ('불', '🔥', TRUE, 1),
    ('흙', '🌍', TRUE, 1),
    ('공기', '💨', TRUE, 1)
ON CONFLICT (name) DO NOTHING;

-- 7. 인덱스 생성 (성능 최적화)
CREATE INDEX IF NOT EXISTS idx_elements_name ON elements(name);
CREATE INDEX IF NOT EXISTS idx_elements_depth ON elements(depth);
CREATE INDEX IF NOT EXISTS idx_recipes_result ON recipes(result);
CREATE INDEX IF NOT EXISTS idx_daily_challenges_date ON daily_challenges(date);
CREATE INDEX IF NOT EXISTS idx_daily_progress_user_date ON daily_progress(user_id, date);
