-- 일일공방 (Daily Workshop) 데이터베이스 스키마
-- Supabase PostgreSQL에서 실행

-- 1. 유저 테이블 (익명 로그인 지원)
CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    username VARCHAR(50) UNIQUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    gold INTEGER DEFAULT 0
);

-- 2. 원소(단어) 테이블
CREATE TABLE IF NOT EXISTS elements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    emoji VARCHAR(10),
    is_base_element BOOLEAN DEFAULT FALSE,
    discovered_by UUID REFERENCES users(id),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. 조합 레시피 테이블
CREATE TABLE IF NOT EXISTS recipes (
    input_a BIGINT REFERENCES elements(id),
    input_b BIGINT REFERENCES elements(id),
    result BIGINT REFERENCES elements(id),
    PRIMARY KEY (input_a, input_b)
);

-- 4. 일일 진행 상황 테이블
CREATE TABLE IF NOT EXISTS daily_progress (
    user_id UUID REFERENCES users(id),
    date DATE DEFAULT CURRENT_DATE,
    found_elements BIGINT[],
    move_count INTEGER DEFAULT 0,
    is_completed BOOLEAN DEFAULT FALSE,
    completed_at TIMESTAMPTZ,
    PRIMARY KEY (user_id, date)
);

-- 5. 기본 4원소 삽입
INSERT INTO elements (name, emoji, is_base_element) VALUES
    ('물', '💧', TRUE),
    ('불', '🔥', TRUE),
    ('흙', '🌍', TRUE),
    ('공기', '💨', TRUE)
ON CONFLICT (name) DO NOTHING;

-- 6. 인덱스 생성 (성능 최적화)
CREATE INDEX IF NOT EXISTS idx_elements_name ON elements(name);
CREATE INDEX IF NOT EXISTS idx_recipes_result ON recipes(result);
CREATE INDEX IF NOT EXISTS idx_daily_progress_user_date ON daily_progress(user_id, date);
